export const DEFAULT_NAV_CATEGORIES = [
  { name: 'Academics', order: 1 },
  { name: 'Administration', order: 2 },
  { name: 'Reports and Communication', order: 3 },
];

export const DEFAULT_NAV_ITEMS = [
  { name: "Dashboard", route: "/", icon: "Home", role: "center", feature_name: "dashboard_access", category: null, order: 0 },

  // Academics Group
  { name: "Take Attendance", route: "/attendance", icon: "CheckSquare", role: "center", feature_name: "take_attendance", category: 'Academics', order: 1 },
  { name: "Class Routine", route: "/class-routine", icon: "Clock", role: "center", feature_name: "class_routine", category: 'Academics', order: 2 },
  { name: "Lesson Plans", route: "/lesson-plans", icon: "LayoutList", role: "center", feature_name: "lesson_plans", category: 'Academics', order: 3 },
  { name: "Lesson Plan Management", route: "/lesson-plan-management", icon: "ClipboardCheck", role: "center", feature_name: "lesson_plans", category: 'Academics', order: 4 },
  { name: "Lesson Tracking", route: "/lesson-tracking", icon: "BookOpen", role: "center", feature_name: "lesson_tracking", category: 'Academics', order: 5 },
  { name: "Homework", route: "/homework", icon: "Book", role: "center", feature_name: "homework_management", category: 'Academics', order: 6 },
  { name: "Tests", route: "/tests", icon: "ClipboardCheck", role: "center", feature_name: "test_management", category: 'Academics', order: 7 },
  { name: "Exams & Results", route: "/exams", icon: "GraduationCap", role: "center", feature_name: "exams_results", category: 'Academics', order: 8 },
  { name: "Published Results", route: "/published-results", icon: "Award", role: "center", feature_name: "published_results", category: 'Academics', order: 9 },
  { name: "Activities", route: "/activities", icon: "Paintbrush", role: "center", feature_name: "preschool_activities", category: 'Academics', order: 10 },
  { name: "Discipline", route: "/discipline", icon: "AlertTriangle", role: "center", feature_name: "discipline_issues", category: 'Academics', order: 11 },

  // Administration Group
  { name: "Students Registration", route: "/register", icon: "UserPlus", role: "center", feature_name: "register_student", category: 'Administration', order: 12 },
  { name: "Teachers Registration", route: "/teachers", icon: "Users", role: "center", feature_name: "teacher_management", category: 'Administration', order: 13 },
  { name: "Teachers' Attendance", route: "/teacher-attendance", icon: "UserCheck", role: "center", feature_name: "teachers_attendance", category: 'Administration', order: 14 },
  { name: "HR Management", route: "/hr-management", icon: "Award", role: "center", feature_name: "hr_management", category: 'Administration', order: 15 },
  { name: "Leave Management", route: "/leave-management", icon: "Plane", role: "center", feature_name: "leave_management", category: 'Administration', order: 16 },
  { name: "Student ID Cards", route: "/student-id-cards", icon: "IdCard", role: "center", feature_name: "student_id_cards", category: 'Administration', order: 17 },
  { name: "Inventory & Assets", route: "/inventory", icon: "Archive", role: "center", feature_name: "inventory_assets", category: 'Administration', order: 18 },
  { name: "Transport & Tracking", route: "/transport", icon: "Bus", role: "center", feature_name: "transport_tracking", category: 'Administration', order: 19 },
  { name: "School Days", route: "/school-days", icon: "CalendarDays", role: "center", feature_name: "school_days", category: 'Administration', order: 20 },
  { name: "Settings", route: "/settings", icon: "Settings", role: "center", feature_name: "settings_access", category: 'Administration', order: 21 },

  // Reports and Communication Group
  { name: "Messages", route: "/messages", icon: "MessageSquare", role: "center", feature_name: "messaging", category: 'Reports and Communication', order: 22 },
  { name: "Meetings", route: "/meetings", icon: "Video", role: "center", feature_name: "meetings_management", category: 'Reports and Communication', order: 23 },
  { name: "Calendar & Events", route: "/calendar", icon: "CalendarDays", role: "center", feature_name: "calendar_events", category: 'Reports and Communication', order: 24 },
  { name: "Student Report", route: "/student-report", icon: "User", role: "center", feature_name: "student_report", category: 'Reports and Communication', order: 25 },
  { name: "Attendance Summary", route: "/attendance-summary", icon: "Calendar", role: "center", feature_name: "attendance_summary", category: 'Reports and Communication', order: 26 },
  { name: "Summary", route: "/summary", icon: "BarChart3", role: "center", feature_name: "summary", category: 'Reports and Communication', order: 27 },
  { name: "Teacher Reports", route: "/teacher-performance", icon: "BarChart3", role: "center", feature_name: "teacher_reports", category: 'Reports and Communication', order: 28 },
  { name: "Chapter Performance", route: "/chapter-performance-overview", icon: "TrendingUp", role: "center", feature_name: "chapter_performance", category: 'Reports and Communication', order: 29 },
  { name: "View Records", route: "/records", icon: "FileText", role: "center", feature_name: "view_records", category: 'Reports and Communication', order: 30 },
  { name: "Finance", route: "/finance", icon: "DollarSign", role: "center", feature_name: "finance", category: 'Reports and Communication', order: 31 },
  { name: "About Institution", route: "/about-institution", icon: "Building", role: "center", feature_name: "about_institution", category: null, order: 32 },

  // Teacher Defaults
  { name: "Dashboard", route: "/teacher-dashboard", icon: "Home", role: "teacher", feature_name: "dashboard_access", category: null, order: 0 },
  { name: "Take Attendance", route: "/teacher/take-attendance", icon: "CheckSquare", role: "teacher", feature_name: "take_attendance", category: 'Academics', order: 1 },
  { name: "Lesson Plans", route: "/teacher/lesson-plans", icon: "LayoutList", role: "teacher", feature_name: "lesson_plans", category: 'Academics', order: 2 },
  { name: "Students Registration", route: "/register", icon: "UserPlus", role: "teacher", feature_name: "register_student", category: 'Administration', order: 11 },
  { name: "Teachers Registration", route: "/teachers", icon: "Users", role: "teacher", feature_name: "teacher_management", category: 'Administration', order: 12 },
  { name: "Teachers' Attendance", route: "/teacher-attendance", icon: "UserCheck", role: "teacher", feature_name: "teachers_attendance", category: 'Administration', order: 13 },
  { name: "HR Management", route: "/hr-management", icon: "Award", role: "teacher", feature_name: "hr_management", category: 'Administration', order: 14 },
  { name: "Leave Management", route: "/teacher/leave", icon: "Plane", role: "teacher", feature_name: "leave_management", category: 'Administration', order: 15 },
  { name: "Student ID Cards", route: "/student-id-cards", icon: "IdCard", role: "teacher", feature_name: "student_id_cards", category: 'Administration', order: 16 },
  { name: "Inventory & Assets", route: "/inventory", icon: "Archive", role: "teacher", feature_name: "inventory_assets", category: 'Administration', order: 17 },
  { name: "Transport & Tracking", route: "/transport", icon: "Bus", role: "teacher", feature_name: "transport_tracking", category: 'Administration', order: 18 },
  { name: "School Days", route: "/school-days", icon: "CalendarDays", role: "teacher", feature_name: "school_days", category: 'Administration', order: 19 },
  { name: "Lesson Tracking", route: "/teacher/lesson-tracking", icon: "BookOpen", role: "teacher", feature_name: "lesson_tracking", category: 'Academics', order: 3 },
  { name: "Homework", route: "/teacher/homework-management", icon: "Book", role: "teacher", feature_name: "homework_management", category: 'Academics', order: 4 },
  { name: "Tests", route: "/teacher/test-management", icon: "ClipboardCheck", role: "teacher", feature_name: "test_management", category: 'Academics', order: 5 },
  { name: "Exams & Results", route: "/teacher/exams", icon: "GraduationCap", role: "teacher", feature_name: "exams_results", category: 'Academics', order: 6 },
  { name: "Published Results", route: "/teacher/published-results", icon: "Award", role: "teacher", feature_name: "published_results", category: 'Academics', order: 7 },
  { name: "Marks Entry", route: "/teacher/marks-entry", icon: "PenTool", role: "teacher", feature_name: "test_management", category: 'Academics', order: 8 },
  { name: "My Attendance", route: "/teacher/my-attendance", icon: "Clock", role: "teacher", feature_name: "teachers_attendance", category: 'Academics', order: 9 },
  { name: "Activities", route: "/teacher/activities", icon: "Paintbrush", role: "teacher", feature_name: "preschool_activities", category: 'Academics', order: 10 },
  { name: "Discipline", route: "/teacher/discipline-issues", icon: "AlertTriangle", role: "teacher", feature_name: "discipline_issues", category: 'Academics', order: 11 },
  { name: "Class Routine", route: "/teacher/class-routine", icon: "Clock", role: "teacher", feature_name: "class_routine", category: 'Academics', order: 12 },
  { name: "Chapter Performance", route: "/teacher/chapter-performance", icon: "TrendingUp", role: "teacher", feature_name: "chapter_performance", category: 'Administration', order: 13 },
  { name: "Settings", route: "/teacher/settings", icon: "Settings", role: "teacher", feature_name: "settings_access", category: 'Administration', order: 14 },
  { name: "Messages", route: "/teacher-messages", icon: "MessageSquare", role: "teacher", feature_name: "messaging", category: 'Reports and Communication', order: 15 },
  { name: "Meetings", route: "/teacher-meetings", icon: "Video", role: "teacher", feature_name: "meetings_management", category: 'Reports and Communication', order: 16 },
  { name: "Calendar", route: "/teacher/calendar", icon: "Calendar", role: "teacher", feature_name: "calendar_events", category: 'Reports and Communication', order: 17 },
  { name: "Student Report", route: "/teacher/student-report", icon: "User", role: "teacher", feature_name: "student_report", category: 'Reports and Communication', order: 18 },
  { name: "Attendance Summary", route: "/teacher/attendance-summary", icon: "CalendarDays", role: "teacher", feature_name: "attendance_summary", category: 'Reports and Communication', order: 19 },
  { name: "Summary", route: "/teacher/summary", icon: "BarChart3", role: "teacher", feature_name: "summary", category: 'Reports and Communication', order: 20 },
  { name: "View Records", route: "/teacher/view-records", icon: "FileText", role: "teacher", feature_name: "view_records", category: 'Reports and Communication', order: 21 },
  { name: "Finance", route: "/teacher/finance", icon: "DollarSign", role: "teacher", feature_name: "finance", category: 'Reports and Communication', order: 22 },
  { name: "AI Insights", route: "/teacher/ai-insights", icon: "Brain", role: "teacher", feature_name: "ai_insights", category: 'Reports and Communication', order: 24 },
  { name: "About Institution", route: "/teacher/about-institution", icon: "Building", role: "teacher", feature_name: "about_institution", category: null, order: 25 },

  // Parent Defaults
  { name: "Dashboard", route: "/parent-dashboard", icon: "Home", role: "parent", feature_name: "dashboard_access", category: null, order: 0 },
  { name: "Lesson Tracking", route: "/parent-lesson-tracking", icon: "BookOpen", role: "parent", feature_name: "lesson_tracking", category: 'Academics', order: 1 },
  { name: "Exam Results", route: "/parent-results", icon: "GraduationCap", role: "parent", feature_name: "exams_results", category: 'Academics', order: 2 },
  { name: "Homework", route: "/parent-homework", icon: "Book", role: "parent", feature_name: "homework_management", category: 'Academics', order: 3 },
  { name: "Activities", route: "/parent-activities", icon: "Paintbrush", role: "parent", feature_name: "preschool_activities", category: 'Academics', order: 4 },
  { name: "Discipline", route: "/parent-discipline", icon: "AlertTriangle", role: "parent", feature_name: "discipline_issues", category: 'Academics', order: 5 },
  { name: "Settings", route: "/parent-settings", icon: "Settings", role: "parent", feature_name: "settings_access", category: 'Administration', order: 6 },
  { name: "Messages", route: "/parent-messages", icon: "MessageSquare", role: "parent", feature_name: "messaging", category: 'Reports and Communication', order: 7 },
  { name: "Meetings", route: "/parent-meetings", icon: "Video", role: "parent", feature_name: "meetings_management", category: 'Reports and Communication', order: 8 },
  { name: "Student Report", route: "/parent-student-report", icon: "BarChart3", role: "parent", feature_name: "student_report", category: 'Reports and Communication', order: 9 },
  { name: "Calendar", route: "/parent-calendar", icon: "Calendar", role: "parent", feature_name: "calendar_events", category: 'Reports and Communication', order: 10 },
  { name: "Finance", route: "/parent-finance", icon: "DollarSign", role: "parent", feature_name: "finance", category: 'Reports and Communication', order: 11 },
  { name: "Leave Applications", route: "/parent-leave", icon: "Plane", role: "parent", feature_name: "leave_management", category: 'Reports and Communication', order: 12 },
  { name: "Chapter Rating", route: "/parent-chapter-rating", icon: "Star", role: "parent", feature_name: "chapter_performance", category: 'Reports and Communication', order: 13 },
  { name: "About Institution", route: "/parent-about-institution", icon: "Building", role: "parent", feature_name: "about_institution", category: null, order: 14 },
];
